name: "Semantic Versioning"
description: "Automatic semantic versioning based on branch naming conventions. Supports major, minor, patch bumps and pre-release tags."
author: "TheKathan"

inputs:
  major-version:
    description: "Major version number"
    required: false
    default: "1"
  enable-prerelease:
    description: "Enable pre-release versioning on feature/fix branches"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}
  branch-patterns:
    description: "Custom branch patterns (JSON format). Example: {\"major\":[\"breaking/*\"],\"minor\":[\"feature/*\",\"feat/*\"],\"patch\":[\"fix/*\",\"hotfix/*\"]}"
    required: false
    default: ""
  comment-on-pr:
    description: "Add comment to PR with calculated version"
    required: false
    default: "false"
  add-to-summary:
    description: "Add version to GitHub Actions job summary"
    required: false
    default: "false"

outputs:
  version:
    description: "Calculated semantic version"
    value: ${{ steps.version.outputs.version }}
  is-prerelease:
    description: "Whether this is a pre-release version"
    value: ${{ steps.version.outputs.is_prerelease }}

runs:
  using: "composite"
  steps:
    - name: Calculate Version
      id: version
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -x
        git fetch --all --tags --force
        echo "Fetched tags"

        CURRENT_TAG=$(git tag --points-at HEAD | grep -E "^v[0-9]" | sort -V | tail -n 1 || true)
        echo "Current tag: $CURRENT_TAG"
        if [ -n "$CURRENT_TAG" ]; then
          echo "version=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "skip_tag=true" >> $GITHUB_OUTPUT
          [[ "$CURRENT_TAG" =~ -[a-z]+\.[0-9]+$ ]] && echo "is_prerelease=true" >> $GITHUB_OUTPUT || echo "is_prerelease=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        echo "Branch: $BRANCH"

        LATEST=$(git tag | grep -E "^v${{ inputs.major-version }}\.[0-9]+\.[0-9]+$" | sort -V | tail -n 1 || true)
        LATEST="${LATEST:-v${{ inputs.major-version }}.0.0}"
        IFS='.' read -r MAJ MIN PAT <<< "${LATEST#v}"
        echo "Version base: $MAJ.$MIN.$PAT"

        if [[ "$BRANCH" == "main" ]]; then
          echo "On main branch, checking PR source"
          SOURCE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls" | \
            jq -r '.[0].head.ref // empty' 2>/dev/null || echo "")
          echo "PR source branch: $SOURCE"

          case "$SOURCE" in
            feature/*|feat/*) MIN=$((MIN + 1)); PAT=0 ;;
            fix/*|hotfix/*|bugfix/*|chore/*|docs/*|refactor/*|perf/*|performance/*|test/*|tests/*|build/*|ci/*|style/*) PAT=$((PAT + 1)) ;;
            *) PAT=$((PAT + 1)) ;;
          esac

          VERSION="v$MAJ.$MIN.$PAT"
          echo "is_prerelease=false" >> $GITHUB_OUTPUT

        elif [[ "${{ inputs.enable-prerelease }}" == "true" ]]; then
          case "$BRANCH" in
            feature/*|feat/*)
              MIN=$((MIN + 1)); PAT=0; SUFFIX="alpha"
              ;;
            fix/*|hotfix/*|bugfix/*)
              PAT=$((PAT + 1)); SUFFIX="fix"
              ;;
            chore/*)
              PAT=$((PAT + 1)); SUFFIX="chore"
              ;;
            docs/*)
              PAT=$((PAT + 1)); SUFFIX="docs"
              ;;
            refactor/*)
              PAT=$((PAT + 1)); SUFFIX="refactor"
              ;;
            perf/*|performance/*)
              PAT=$((PAT + 1)); SUFFIX="perf"
              ;;
            test/*|tests/*)
              PAT=$((PAT + 1)); SUFFIX="test"
              ;;
            build/*)
              PAT=$((PAT + 1)); SUFFIX="build"
              ;;
            ci/*)
              PAT=$((PAT + 1)); SUFFIX="ci"
              ;;
            style/*)
              PAT=$((PAT + 1)); SUFFIX="style"
              ;;
            *)
              echo "Branch '$BRANCH' does not match expected patterns"
              exit 1
              ;;
          esac

          COUNTER=$(git tag | grep -E "^v${MAJ}\.${MIN}\.${PAT}-${SUFFIX}\.[0-9]+$" | \
            tail -n 1 | grep -oE "[0-9]+$" || echo "0")
          VERSION="v$MAJ.$MIN.$PAT-$SUFFIX.$((COUNTER + 1))"
          echo "is_prerelease=true" >> $GITHUB_OUTPUT

        else
          echo "Not on main and pre-release disabled. Skipping versioning."
          exit 1
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT

        # Add to job summary if enabled
        if [[ "${{ inputs.add-to-summary }}" == "true" ]]; then
          echo "## 📦 Version: \`$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "- **Type**: Pre-release" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Type**: Release" >> $GITHUB_STEP_SUMMARY
          fi
        fi

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        IS_PRERELEASE="${{ steps.version.outputs.is_prerelease }}"

        if [[ "$IS_PRERELEASE" == "true" ]]; then
          TYPE="Pre-release"
          NOTE="Will be published as pre-release tag"
        else
          TYPE="Release"
          NOTE="Will be published when merged to main"
        fi

        gh pr comment ${{ github.event.pull_request.number }} --body "## 📦 Version Preview

This PR will create version: **$VERSION**

- Type: **$TYPE**
- $NOTE"

    - name: Push Tag
      if: steps.version.outputs.skip_tag != 'true'
      shell: bash
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        IS_PRERELEASE="${{ steps.version.outputs.is_prerelease }}"

        git tag "$VERSION"
        git push origin "$VERSION"

        if [[ "$IS_PRERELEASE" == "false" ]]; then
          MAJOR_TAG=$(echo "$VERSION" | grep -oE "^v[0-9]+" || true)
          if [[ -n "$MAJOR_TAG" ]]; then
            echo "Updating major version tag: $MAJOR_TAG"
            git tag -f "$MAJOR_TAG" "$VERSION"
            git push origin "$MAJOR_TAG" --force
          fi
        fi

branding:
  icon: "package"
  color: "green"
