name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: The action failed to create a tag when...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have created tag v1.2.3
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration
      description: Share your workflow YAML
      render: yaml
      placeholder: |
        - uses: TheKathan/semantic-versioning@v1
          with:
            major-version: "1"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Action Version
      description: Which version are you using? (e.g., v1, v1.0.4)
      placeholder: v1
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste relevant error messages or logs
      render: shell
